[package]
name = "region_quadtree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.7"
serde = { version = "1.0.193", features = ["derive"] }
serde-pickle = "1.1.1"